### PR TITLE
Solved undo deleted item.

### PR DESCRIPTION
**Pull request by flaviu22**
I have solved the missing feature option -> Undo deleted item.

### CODE REVIEW

**Comment by derceg** [comment]
Thanks for this. As a start, could you reduce this down to only the necessary changes. At the moment, this pull request includes both unrelated changes (e.g. adding a `Ctrl+Q` accelerator) as well as unnecessary changes (e.g. formatting changes, use of `CComPtr` instead of `wil::com_ptr_nothrow`, changes to the resource headers, changes to `ShellBrowserImpl.cpp` and `ShellTreeView.cpp`).

**Comment by flaviu22** [comment]
Ok, I will try to let only necessary changes, so, I should add Ctrl+Q shortcut to another pull request? Will you accept this new pull request? I am asking this to know if I should prepare another pull request.

Of course, this is not a condition, I will filter the current pull request to what it needs, but for me this shortcut is also handy. And I am sure not only for me :)

**Comment by flaviu22** [comment]
See the following method:

```
HRESULT FileOperations::Undelete(const PCIDLIST_ABSOLUTE &pidl)
{
	wil::com_ptr_nothrow<IShellFolder> pDesktop{};
	HRESULT hr = SHGetDesktopFolder(&pDesktop);
	if (SUCCEEDED(hr) && pDesktop)
	{
//		CComHeapPtr<ITEMIDLIST_ABSOLUTE> pidlbin{};
		wil::com_ptr_nothrow<ITEMIDLIST_ABSOLUTE> pidlbin;
		hr = SHGetKnownFolderIDList(FOLDERID_RecycleBinFolder, KF_FLAG_DEFAULT, NULL, &pidlbin);
		if (SUCCEEDED(hr) && pidlbin)
		{
			wil::com_ptr_nothrow<IShellFolder> pShellFolder{};
			hr = pDesktop->BindToObject(pidlbin.get(), nullptr, IID_PPV_ARGS(&pShellFolder));
			if (SUCCEEDED(hr) && pShellFolder)
			{
				wil::com_ptr_nothrow<IEnumIDList> pEnum{};
				hr = pShellFolder->EnumObjects(NULL, SHCONTF_FOLDERS | SHCONTF_NONFOLDERS, &pEnum);
				if (SUCCEEDED(hr) && pEnum)
				{
					ULONG fetched{};
					for (PITEMID_CHILD pidChild{}; pEnum->Next(1, &pidChild, &fetched) == S_OK; pidChild = nullptr)
					{
						const auto pidlRelative = ILFindLastID(static_cast<PCUIDLIST_RELATIVE>(pidl));
						hr = pShellFolder->CompareIDs(SHCIDS_CANONICALONLY, pidlRelative, pidChild);
						if (0 == static_cast<short>(HRESULT_CODE(hr)))
						{
							hr = PerformUndeleting(pShellFolder, pidChild);
							break;
						}
					}
				}
			}
		}
	}

	return hr;
}

```
I don't think I can remove `CComHeapPtr` from this method, I get:

`30>C:\Project\explorerplusplus\vcpkg_installed\x64-windows-static\x64-windows-static\include\wil\com.h(263,20): error C2039: 'Release': is not a member of '_ITEMIDLIST_ABSOLUTE'
`
if I use wil::com_ptr_nothrow instead of `CComHeapPtr` for `pidlbin`.

**Comment by flaviu22** [comment]
I'll come out with another pull request.

**Comment by derceg** [comment]
> Ok, I will try to let only necessary changes, so, I should add Ctrl+Q shortcut to another pull request? Will you accept this new pull request? I am asking this to know if I should prepare another pull request.

Pull requests for new shortcuts are fine in general. In this specific case, I'm not really a fan of adding Ctrl+Q as a default shortcut, since Q is right next to W, making it easy to accidentally close the application, instead of closing the current tab. I've had that happen to me in other applications, for example. There's ongoing work (tracked in #476) to allow keyboard shortcuts to be customised, so once that's done, you could add Ctrl+Q as a user shortcut, without having to modify the code.

**Comment by flaviu22** [comment]
So, the undo deelted changes will be rejected? Have you seen I removed that Ctrl+Q shortcut? That's why I named - clean code the pull request.

**Comment by derceg** [comment]
Sorry, I meant I wasn't really in favor of adding a Ctrl+Q shortcut, specifically. I'm still planning on reviewing the changes in the updated pull request.

**Comment by flaviu22** [comment]
Another option will be to have Ctrl+Shift+W as Quit accelerator.

**Pull request closed without merging**
