### PR TITLE
pre-cache file data when enumerating folders on network drives

### PR DESCRIPTION
**Pull request by sean-e**
fix for #262

### CODE REVIEW

**Comment by sean-e** [comment]
A simple modification to this PR would also improve performance on local drives as well.

**Comment by sean-e** [comment]
@derceg This PR improves performance on network drives, particularly for folders with thousands of items.

**Comment by derceg** [comment]
I think it would be better to remove the call to `FindFirstFile` altogether and simply retrieve the basic information required for each file (file size, creation/modification/access dates, file attributes) instead.

The enumeration used to be based off `FindFirstFile`/`FindNextFile` entirely, but those functions don't handle non-filesystem folders. So then the implementation was switched to `IShellFolder::EnumObjects`, since it can enumerate any folder.

But there was already code that depended on having easy access to the data contained in the `WIN32_FIND_DATA` struct (something that's still true now), which is why the call to `FindFirstFile` is there.

Rather than call `FindFirstFile` at all, it would probably be better to specifically retrieve what's needed, instead of enumerating the directory twice.

The idea I have in mind would be to use `IShellFolder2::GetDetailsEx` to retrieve:

`PKEY_Size`
`PKEY_DateAccessed`
`PKEY_DateCreated`
`PKEY_DateModified`
`PKEY_FileAttributes`

I'm not sure how the performance of doing that might differ to calling `FindNextFile` in a loop. From looking at the Wine source code, `FindNextFile` ultimately retrieves the data using [`NtQueryDirectoryFile`](https://github.com/wine-mirror/wine/blob/e909986e6ea5ecd49b2b847f321ad89b2ae4f6f1/dlls/kernelbase/file.c#L1372).

It could be that calling `FindFirstFile` repeatedly, instead of `FindFirstFile` + `FindNextFile` is inefficient. In the Wine implementation, `FindFirstFile` [calls through](https://github.com/wine-mirror/wine/blob/e909986e6ea5ecd49b2b847f321ad89b2ae4f6f1/dlls/kernelbase/file.c#L1272) to `FindNextFile`, so `FindFirstFile` probably does some setup work and if you call it repeatedly, that work would be done multiple times.

I have done a basic test comparing the current `FindFirstFile` approach to `IShellFolder2::GetDetailsEx` (when retrieving the five properties listed above). For a folder with 25,000 items, I measured the approximate time spent in `EnumerateFolder`:

FindFirstFile: ~12s
IShellFolder2::GetDetailsEx: ~3.5s

The absolute numbers aren't very relevant, but the difference is important and `IShellFolder2::GetDetailsEx` seems to work out better. So I think using `IShellFolder2::GetDetailsEx` would be the way forward.

I don't think that could easily be done in a pull request, however, so I'll make that change and close this pull request. It is a good thing you pointed out the issue, though. The current method of using `FindFirstFile` is clearly suboptimal.

**Comment by KrokusPokus** [comment]
It's said that in a FindFirstFile+FindNextFile loop, the OS reads ahead and precaches data, so when you ask for the data to the one item, the OS would actually read and prepare the data for the next 100+ items in advance. Calling FindFirstFile repeatedly basically throws these effords away and starts from scratch everytime.

**Pull request closed without merging**
