### PR TITLE
fix for uncaught exception when opening new tab in Details view

### PR DESCRIPTION
**Pull request by sean-e**

### CODE REVIEW

**Comment by account-sxf** [comment]
From testing this looks to happen because "This PC" can't be displayed in detailed view. Steps to reproduce include setting details view to be the default for new tabs. If we could customize the path to open for new tabs we could work around this issue.

**Comment by sean-e** [comment]
"This PC" does work in detail view, aside for some columns that don't.  This PR addresses that problem.

**Comment by derceg** [comment]
So the reason this happens is that one of the column types that was present in 1.3.5 was removed, which causes the various column lookups to fail. The exception in this case is meant to catch these sorts of issues and catching the exception isn't really sufficient, because other asserts will be triggered and calls that shouldn't fail will.

The column type (CM_VIRTUALTYPE) was actually removed all the way back in 2011:

https://github.com/derceg/explorerplusplus/commit/0781704750feaae773306938dfdf890b33c4ae58#diff-368e58556a7e730bbfa7b6130e6f3b13L193

The column was unified with CM_TYPE.

Although the change was made well before 1.3.5 was released, it never made it into that version, which is why this has only being an issue in more recent builds.

Ultimately, what needs to happen is for that column to be transformed when it's loaded. In other words, if column "32" is loaded, it needs to be changed to ColumnType::Type.

@sean-e If you want to make that change, I'm happy to review. Otherwise, I'll take a look.

**Comment by sean-e** [comment]
Sure, I'll take a look this weekend.

**Comment by sean-e** [comment]
I'm closing this PR to create a new one

**Comment by sean-e** [comment]
> @sean-e If you want to make that change, I'm happy to review. Otherwise, I'll take a look.

@derceg Any chance of having you review my open pull requests?

**Pull request closed without merging**
